name: "Destroy Infrastructure"
on:
  workflow_dispatch:

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./infra"

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      
      # Checkout checks out the current configuration
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install Terraform on Runner using Terraform API Token
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        id: install-tf
        with:
          cli_config_credentials_token:  ${{ secrets.TF_API_TOKEN }}
          directory: ${{ env.CONFIG_DIRECTORY }}
      
      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: |
         cd ./infra/
         terraform init

      
      # Apply confirms and applies the run
      - name: Terraform Destroy
        id: destroy
        run: |
         cd ./infra/
         terraform destroy --auto-approve